### ISSUE TITLE
Grch38 version of mutation calls

### ISSUE THREAD

**Issue by kiranchari** [ding-lab/PanCanAtlasGermline#4]
Hi,

The released PanCan mutation calls are based on GRch37. However, GDC has updated the TCGA data to use GRch38.

Is there a GRch38 version of the filtered germline mutation calls for TCGA (PCA.r1.TCGAbarcode.merge.tnSwapCorrected.10389.vcf.gz)?

**Comment by kuanlinhuang** [comment]
There's not, if we get to it or any research group would like to help
that'd be amazing

**Comment by kiranchari** [comment]
@kuanlinhuang Can we just convert the hg19 coordinates to hg38 using liftover (https://pypi.org/project/liftover/)?

**Comment by kuanlinhuang** [comment]
Ya that's a good idea
(Ideally we also have to reclassify based on new ClinVar etc evidence, but
liftover shall def be fine)

**Comment by kiranchari** [comment]
Great thanks.

**Comment by kiranchari** [comment]
@kuanlinhuang I converted the PanCan germline calls to hg38 using liftover. However, I found that some of the germline sites (not all) have _zero_ supporting reads for the alternate allele in the corresponding BAM file from GDC. Is it expected to lose some variants when converting from hg19 to hg38 due to alignment differences? I presume the underlying sequencing reads were the same for the PanCan study vs GDC bams. Appreciate your input on this. Thanks.

**Comment by kuanlinhuang** [comment]
The original calls were read counted and manual reviewed with igv. So if
you're seeing that for many variants please double check your pipeline

I did have a recent discussion with a collaborator who showed me data that
alignment and calling to the two versions actually yielded different
results sometimes even for snv/indels.... Most ideally we align to t2t or
graph genome in the future

**Comment by kiranchari** [comment]
Thanks for your response. I only checked a few variants manually - I will check the read counts for a larger sample of variants and report back.
